version: "3.9"
services:
  alarm-mysql:
    image: mysql:8.2.0
    restart: always
    ports:
      - 28100:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: alarm
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./.docker/mysql/:/var/lib/mysql
      - ./infra/:/docker-entrypoint-initdb.d
    networks:
      - lalala-network

  alarm-redis:
    image: redis:7.0
    ports:
      - 28200:6379

  alarm-adminer:
    image: adminer
    restart: always
    ports:
      - 29900:8080

  alarm-rabbitmq:
    image: rabbitmq:3.10-management
    ports:
      - "28300:5672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

networks:
  lalala-network:
    driver: bridge
    external: true
