version: "3.9"

services:
  chart-mongo:
    image: mongo:7.0.5
    container_name: chart-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: chipmunk
      MONGO_INITDB_ROOT_PASSWORD: JMTpdsu8YkLEXBW4RA
      MONGO_INITDB_DATABASE: chart
    volumes:
      - chart-mongodbdata:/data/db:cached
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  chart-mongo-express:
    image: mongo-express:1.0.2
    restart: always
    ports:
      - 27000:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: chipmunk
      ME_CONFIG_MONGODB_ADMINPASSWORD: JMTpdsu8YkLEXBW4RA
      ME_CONFIG_MONGODB_SERVER: chart-mongo
      ME_CONFIG_BASICAUTH_USERNAME: chipmunk-admin
      ME_CONFIG_BASICAUTH_PASSWORD: g2+u*8XG%^xKT=-SzDMfbZ

volumes:
  chart-mongodbdata:
    driver: local
