server:
  port: 22000
#  servlet:
#    container: none
#  websocket:
#    server:
#      path: /v1/ws
#  netty:
#    worker-count: 2

  application:
    name: streaming-server

  kafka:
    bootstrap-servers: localhost:40000,localhost:40001,localhost:40002

client:
  endpoint:
    music: http://localhost:24000
    storage: http://localhost:30000

ffmpeg:
  location:
    mpeg: ./libs/ffmpeg-6.1/ffmpeg
    probe: ./libs/ffmpeg-6.1/ffprobe

passport:
  algorithm: HmacSHA256
  key: SECRET_KEY

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: [b3, w3c]
      produce: [b3, w3c]
  zipkin:
    tracing:
      endpoint: "http://localhost:43000/api/v2/spans"

logging:
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"
