version: '3.9'

services:
  streaming-app:
    ports:
      - "22000:22000"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - client.endpoint.music=http://music-app:24000
      - client.endpoint.storage=http://fileserver-app:30000
      - spring.kafka.bootstrap-servers=Kafka00Service:9092,Kafka01Service:9092,Kafka02Service:9092
      - eureka.instance.hostname=streaming-app
      - passport.algorithm=SHA-256
      - passport.key=SECRET_KEY
    restart: always
    networks:
      - lalala-network

networks:
  lalala-network:
    driver: bridge
    external: true
